### ISSUE TITLE
Failed to activate the wordcount package

### ISSUE THREAD

**Issue by sapphire008** [OleMchls/atom-wordcount#101] opened 2018-06-13 00:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package 3.0.0

### Stack Trace

Failed to activate the wordcount package

```
At Cannot find module 'word-regex'

Error: Cannot find module 'word-regex'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at /packages/wordcount/lib/wordcount-view.coffee:15:18)
    at Object.activate (/packages/wordcount/lib/main.coffee:129:12)
    at Package.activateNow (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.27.2/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.27.2/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.27.2/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.27.2/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
     -0:09.6.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
highlight-selected 0.13.1 
markdown-preview-enhanced 0.15.6 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
split-diff 1.5.2 
wordcount 3.0.0 
```

**Comment by OleMchls** [comment] 2018-09-09 06:15
I can't reproduce it, so closing it now. Please reopen with steps to reproduce and more information.

**Closed by OleMchls** 2018-09-09 06:15 UTC
